/* Configuration for gps_common_core generated by Alire */
#ifndef GPS_COMMON_CORE_CONFIG_H
#define GPS_COMMON_CORE_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "gps_common_core"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
